# yaml-language-server: $schema=https://json.schemastore.org/nuejs-site.json

globals: ["@global"]
libs: ["@library"]

site_name: NueJS Template
site_description: A NueJS template for building modern web applications.

# Activate this line to set a base path for the GitHub Pages deployment.
base: /template1

nav:
  - Home: /
  - About: /about.html