# yaml-language-server: $schema=https://json.schemastore.org/nuejs-site.json

globals: ["@global"]
libs: ["@library"]

site_name: NueJS Template
site_description: A NueJS template for building modern web applications.